= downdoc: Down-convert AsciiDoc to Markdown
ifdef::env-github[]
:toc: preamble
:toc-title: Contents
:toclevels: 1
endif::[]

> Rapidly converts AsciiDoc to Markdown.

== What is downdoc?

The downdoc package provides a CLI (command: `downdoc`) and JavaScript function (`downdoc`) to down-convert AsciiDoc to Markdown.
"`But why,`" you may ask?

The reality is, the AsciiDoc format isn't supported everywhere.
For instance, npm package repositories such as https://npmjs.com and https://yarnpkg.com assume the README for a package is in Markdown.
But you're a sensible developer who wants to maintain your README in AsciiDoc.
Enter downdoc.

This project initially started out with a goal to transpile an AsciiDoc README to the Markdown format for npm packaging.
In that regard, it was designed to be just good enough to get the job done.

Over time, downdoc has proven to have broader application.
With downdoc, you can draft content in AsciiDoc even for places where only Markdown is accepted, such as an issue tracker or chat application.
To post in Markdown, run the content through downdoc then paste the result.
downdoc handles the context switch to Markdown so your brain doesn't have to.

== How does it work?

downdoc employs a minimal approach to map the AsciiDoc syntax to Markdown that does not make use of Asciidoctor.
While this gives it the advantage of having no dependencies and being exceptionally fast, it does not support the full AsciiDoc syntax.
It's intended to be used with AsciiDoc documents that were written with this conversion in mind, as a Markdown frontend.

Here's a rough list of the syntax that downdoc current handles:

* document title
* author info and revision lines in document header
* document attribute entries (single-line only; no support for pass macro)
* document attribute references
* part/chapter/section titles and discrete headings (atx-style only)
* block titles
* formatted text (within line; bold, italic, monospace, highlight, phrase w/ line-through role, double curly quotes, curly apostrophe)
* ordered, unordered, and callout lists (1-9 or .)
* nested ordered and unordered lists (marker must start at left margin; use `markdown-list-indent` attribute to control indent size)
* description list (first level only)
* list continuation (no support for ancestor continuation)
* link and URL macros (use `hide-uri-scheme` to hide URL scheme in visible URL)
* escaped bare URLs
* internal xrefs (honors value of `idprefix` and `idseparator` document attributes; no support for natural xref)
* block IDs for document and section titles (only last block attribute line is consulted)
* auto-generated text for internal xrefs (honoring `reftext` attribute, if specified)
* block and inline image macros
* listing and source blocks with optional source language
* diagram blocks (literal block with diagram dialect)
* callout numbers (1-9 or .) in verbatim blocks (one per line)
* attribute references in verbatim blocks (when subs=attributes+ or subs=+attributes is enabled)
* literal paragraphs (auto-detects command prompt and promotes to command code block)
* admonition paragraphs
* Markdown-style blockquotes
* thematic breaks (Markdown-style, e.g., `---`)
* hard line breaks
* ifdef and ifndef preprocessor conditionals
* tables (normal table cells only; no support for cell style)
* collapsible blocks (set the `markdown-collapsible-variant` attribute to `spoiler` to generate Zulip-compatible spoiler block)
* comment lines and blocks
* passthrough blocks
* delimited example and sidebar blocks (delimiter lines removed)

Support for additional syntax may be added in the future.

== Prerequisites

In order to use this extension, you must have Node.js 16.17.0 or higher installed on your machine.

== Install

Use the following command to install the downdoc package into your project:

[,console]
----
$ npm i downdoc
----

Alternately, you can defer installation and invoke the CLI using the `npx` command.

== Usage

=== CLI

[,console]
----
$ npx downdoc README.adoc
----

The `downdoc` command automatically generates a Markdown file.
By default, the Markdown file has the same name as the AsciiDoc file with the file extension changed to `.md` (e.g., `README.md`).

You can instruct the command to write to a different file using the `-o` (or `--output`) option.

[,console]
----
$ npx downdoc -o out.md README.adoc
----

If the value of the `-o` option is `-`, the command will write the output to the console (i.e., stdout).

[,console]
----
$ npx downdoc -o - README.adoc
----

You can pass additional runtime AsciiDoc attributes using the `-a` (or `--attribute`) option.

[,console]
----
$ npx downdoc -a hide-uri-scheme -a markdown-list-indent=4 README.adoc
----

To print a usage statement that includes a complete list of available options, pass the `-h` option.

=== API

[,js]
----
const downdoc = require('downdoc')
const fsp = require('node:fs/promises')

;(async () => {
  await fsp
    .readFile('README.adoc', 'utf8')
    .then((asciidoc) => fsp.writeFile('README.md', downdoc(asciidoc) + '\n', 'utf8'))
})()
----

The `downdoc` function accepts an object (i.e., map) of options as the second argument.

[,js]
----
downdoc(asciidoc, { attributes: { 'markdown-list-indent': 4 } })
----

Currently the only supported option in the API is `attributes`, which is an object (i.e., map) of runtime AsciiDoc attributes.

ifndef::env-npm[]
=== npm publish

The prime focus of this tool is to convert an AsciiDoc README to Markdown for npm packaging.
This switch is done by leveraging the pre and post lifecycle hooks of the `publish` task.
In the pre hook, you convert the README to Markdown and hide the AsciiDoc README.
The npm `publish` task will then discover the Markdown README and include it in the package.
In the post hook, you remove the Markdown README and restore the AsciiDoc README.

Using this technique, the published npm package ends up with a Markdown README, but the README in your repository remains in AsciiDoc.
We refer to this process as the README dance.

If that sounds complicated, no need to worry.
downdoc has you covered.
The downdoc CLI provides the helpers you need to call during these lifecycle hooks.
To use them, add the following entries to the `scripts` property in the [.path]_package.json_ at the root of your project.

[,json]
----
"postpublish": "downdoc --postpublish",
"prepublishOnly": "downdoc --prepublish",
----

Let's have a look at where these entries go when we step back and look at a complete file:

[,json]
----
{
  "name": "my-package",
  "version": "1.0.0",
  "scripts": {
    "postpublish": "downdoc --postpublish",
    "prepublishOnly": "downdoc --prepublish",
    "test": "mocha"
  }
}
----

If you don't want to declare a dependency on the downdoc package in your project, prepend the call to `downdoc` with `npx -y`:

[,json]
----
"postpublish": "npx -y downdoc --postpublish",
"prepublishOnly": "npx -y downdoc --prepublish",
----

When an AsciiDoc file is converted using the `--prepublish` CLI option, both the `env=npm` and `env-npm` document attributes are set.
This allows you to show or hide content in the README that is displayed in the npm package registry.

You can find an example of downdoc used for this purpose in the downdoc project itself.

=== Create executables

Thus far, we've assumed that you're running downdoc using Node.js installed on your system.
However, downdoc is one of those tools you might want to use in any environment.
In that case, what you want is an executable that doesn't require Node.js to be installed.
That's where pkg comes in.

Using https://github.com/vercel/pkg[pkg], you can bundle Node.js and downdoc into a single executable (i.e., a precompiled binary) per system (OS and architecture).
To do so, clone this project and run the following command:

 $ npx pkg -t node18-linux,node18-macos,node18-win .

This command will produce `downdoc-linux`, `downdoc-macos`, and `downdoc-win.exe`.
You can transfer any one of these executables to a suitable system and run it without having to install Node.js.
For example:

 $ ./downdoc-linux README.adoc

The binary includes the package metadata and source code of this project in raw form.
Run `npx pkg -h` or read the https://github.com/vercel/pkg[pkg README] to learn more about how it works.
endif::[]

== Copyright and License

Copyright (C) 2022-present Dan Allen (OpenDevise Inc.) and the individual contributors to this project.

Use of this software is granted under the terms of the MIT License.
