= downdoc: Down-convert AsciiDoc to Markdown
ifdef::env-github[]
:toc: preamble
:toc-title: Contents
:toclevels: 1
endif::[]

> Hastily converts AsciiDoc to Markdown.

== What is downdoc?

The downdoc package provides a JavaScript function and CLI (command: `downdoc`) to down-convert AsciiDoc to Markdown.
But why, you may ask?

The reality is, the AsciiDoc format isn't supported everywhere.
For instance, npm package repositories such as https://npmjs.com and https://yarnpkg.com assume the README for a package is in Markdown.
But you're a sensible developer who wants to maintain your README in AsciiDoc.
Enter downdoc.

This project initially started out with the goal to transpile an AsciiDoc README to the Markdown format for npm packaging.
In that regard, it was designed to be just good enough to get the job done.

Over time, downdoc has proven to have broader application.
With downdoc, you can draft content in AsciiDoc even for places where only Markdown is accepted, such as in an issue tracker or chat application.
To post in Markdown, run the content through downdoc and paste the result.
downdoc handles the context switch to Markdown so your brain doesn't have to.

== How does it work?

downdoc employs a rather crude approach to map the AsciiDoc syntax to Markdown that does not use an AsciiDoc processor.
Therefore, it does not support the full AsciiDoc syntax.
It's intended to be used with simple README files.

Here's a rough list of the syntax it current handles:

* document title
* author info line in document header
* document attribute entries (single-line only)
* document attribute references
* part/chapter/section titles
* block titles
* formatted text (bold, italic, monospace, double curly quotes, curly apostrophe)
* ordered, unordered, and callout lists (1-9)
* nested ordered and unordered lists (marker must start at left margin; use `markdown-list-indent` attribute to control indent size)
* description list (first level only)
* list continuation (basic support)
* link and URL macros
* escaped bare URLs
* internal xrefs (honors value of `idprefix` and `idseparator` document attributes)
* block IDs for document and section titles
* auto-generated text for internal xrefs
* block and inline image macros
* listing and source blocks with optional source language
* diagram blocks (listing block with diagram dialect)
* callout numbers (1-9) in verbatim blocks
* attribute references in verbatim blocks (when attributes sub is enabled)
* literal paragraphs (auto-detects command prompt and promotes to code block)
* admonition paragraphs
* Markdown-style blockquotes
* thematic breaks (Markdown-style, e.g., `---`)
* hard line breaks
* ifdef and ifndef preprocessor conditionals
* collapsible blocks (set the `markdown-collapsible-variant` attribute to `spoiler` to generate Zulip-compatible spoiler block)
* comment lines and blocks
* delimited example and sidebar blocks (unwrapped)
* tables (dropped)

== Prerequisites

In order to use this extension, you need Node.js 16.17.0 or higher.

== Install

Use the following command to install the downdoc package into your project:

[,console]
----
$ npm i downdoc
----

Alternately, you can defer installation and invoke the CLI using npx.

== Usage

=== CLI

[,console]
----
$ npx downdoc README.adoc
----

The `downdoc` command automatically generates a Markdown file.
By default, the Markdown file has the same name as the AsciiDoc file with the file extension changed to `.md`.

You can instruct the command to write to a different file using the `-o` (or `--output`) option.

[,console]
----
$ npx downdoc -o out.md README.adoc
----

If the value of the `-o` option is `-`, the command will write the output to the console (i.e., stdout).

[,console]
----
$ npx downdoc -o - README.adoc
----

=== API

[,js]
----
const downdoc = require('downdoc')
const fsp = require('node:fs/promises')

;(async () => {
  await fsp
    .readFile('README.adoc', 'utf8')
    .then((asciidoc) => fsp.writeFile('README.md', downdoc(asciidoc) + '\n', 'utf8'))
})()
----

ifndef::env-npm[]
=== npm publish

The prime focus of this tool is to convert an AsciiDoc README to Markdown for npm packaging.
This switch is done by leveraging the pre and post lifecycle hooks of the `publish` task.
In the pre hook, you convert the README to Markdown and hide the AsciiDoc README.
The main `publish` task will then discover the Markdown README and include it in the package.
In the post hook, you remove the Markdown README and restore the AsciiDoc README.

Using this technique, the published npm package ends up with a Markdown README, but the README in your repository remains in AsciiDoc.
We refer to this process as the README dance.

If that sounds complicated, no need to worry.
downdoc has you covered.
The downdoc CLI provides the helpers you need to call during these lifecycle hooks.
To use them, add the following entries to the `scripts` property in the [.path]_package.json_ at the root of your project.

[,json]
----
"postpublish": "downdoc --postpublish",
"prepublishOnly": "downdoc --prepublish",
----

Let's have a look at where these entries go when we step back and look at a complete file:

[,json]
----
{
  "name": "my-package",
  "version": "1.0.0",
  "scripts": {
    "postpublish": "downdoc --postpublish",
    "prepublishOnly": "downdoc --prepublish",
    "test": "mocha"
  }
}
----

When an AsciiDoc file is converted using the `--prepublish` CLI option, both the `env=npm` and `env-npm` document attributes are set.
This allows you to show or hide content in the README that is displayed in the npm package registry.

You can find an example of downdoc used for this purpose in the downdoc project itself.

=== Create executables

Thus far, we've assumed that you're running downdoc using Node.js installed on your system.
However, downdoc is one of those tools you might want to use in any environment.
In that case, what you want is an executable that doesn't require Node.js to be installed.
That's where pkg comes in.

Using https://github.com/vercel/pkg[pkg], you can bundle Node.js and downdoc into a single executable (i.e., a precompiled binary) per system (OS and architecture).
To do so, clone this project and run the following command:

 $ npx pkg -t node18-linux,node18-macos,node18-win .

This command will produce `downdoc-linux`, `downdoc-macos`, and `downdoc-win.exe`.
You can transfer any one of these executables to a suitable system and run it without having to install Node.js.
For example:

 $ ./downdoc-linux README.adoc

The binary includes the package metadata and source code of this project in raw form.
Run `npx pkg -h` or read the https://github.com/vercel/pkg[pkg README] to learn more about how it works.
endif::[]

== Copyright and License

Copyright (C) 2022-present Dan Allen (OpenDevise Inc.) and the individual contributors to this project.

Use of this software is granted under the terms of the MIT License.
