= downdoc: Down-convert AsciiDoc to Markdown
ifdef::env-github[]
:toc: preamble
:toc-title: Contents
:toclevels: 1
endif::[]

> Hastily converts AsciiDoc to Markdown.

== What is downdoc?

The downdoc package provides a JavaScript function and CLI (command: `downdoc`) to down-convert AsciiDoc to Markdown.
But why, you may ask?

The reality is, the AsciiDoc format isn't supported everywhere.
For instance, npm package repositories such as https://npmjs.com and https://yarnpkg.com assume the README for a package is in Markdown.
But you're a sensible developer who wants to maintain your README in AsciiDoc.
Enter downdoc.

This project initially started out with the goal to transpile an AsciiDoc README to the Markdown format for npm packaging.
In that regard, it was designed to be just good enough to get the job done.

Over time, downdoc has proven to have broader application.
With downdoc, you can draft content in AsciiDoc even for places where only Markdown is accepted, such as in an issue tracker or chat application.
To post in Markdown, run the content through downdoc and paste the result.
downdoc handles the context switch to Markdown so your brain doesn't have to.

== How does it work?

downdoc employs a rather crude approach to map the AsciiDoc syntax to Markdown that does not use an AsciiDoc processor.
Therefore, it does not support the full AsciiDoc syntax.
It's intended to be used with simple README files.

Here's a rough list of the syntax it current handles:

* document title
* author info line in document header
* document attribute entries in document header (single-line only)
* document attribute references
* part/chapter/section titles
* block titles
* formatted text (bold, italic, monospace)
* ordered, unordered, and callout lists (1-9)
* nested ordered and unordered lists (marker must start at left margin)
* list continuation (top-level list only)
* link and URL macros
* internal xrefs (honors value of `idprefix` and `idseparator` document attributes)
* auto-generated text for internal xrefs
* block and inline image macros
* listing and source blocks with optional language
* diagram blocks (listing block with diagram dialect)
* callout numbers (1-9) in verbatim blocks
* attribute references in verbatim blocks (when attributes sub is enabled)
* literal paragraphs
* admonition paragraphs
* Markdown-style blockquotes
* ifdef and ifndef preprocessor conditionals
* comment lines and blocks
* tables (dropped)

== Prerequisites

In order to use this extension, you must be using at least Node.js 16.

== Install

Use the following command to install the downdoc package into your project:

[,console]
----
$ npm i downdoc
----

Alternately, you can defer installation and invoke the CLI using npx.

== Usage

=== CLI

[,console]
----
$ npx downdoc README.adoc
----

The `downdoc` command automatically generates a Markdown file.
By default, the Markdown file has the same name as the AsciiDoc file with the file extension changed to `.md`.

You can instruct the command to write to a different file using the `-o` (or `--output`) option.

[,console]
----
$ npx downdoc -o out.md README.adoc
----

=== API

[,js]
----
const downdoc = require('downdoc')
const { promises: fsp } = require('node:fs')

;(async () => {
  await fsp
    .readFile('README.adoc', 'utf8')
    .then((asciidoc) => fsp.writeFile('README.md', downdoc(asciidoc) + '\n', 'utf8'))
})()
----

ifndef::env-npm[]
=== npm publish

The prime focus of this tool is to convert an AsciiDoc README to Markdown for npm packaging.
This switch is done by leveraging the pre and post lifecycle hooks of the `publish` task.
In the pre hook, you convert the README to Markdown and hide the AsciiDoc README.
The main `publish` task will then discover the Markdown README and include it in the package.
In the post hook, you remove the Markdown README and restore the AsciiDoc README.

Using this technique, the published npm package ends up with a Markdown README, but the README in your repository remains in AsciiDoc.
We refer to this process as the README dance.

If that sounds complicated, no need to worry.
downdoc has you covered.
The downdoc CLI provides the helpers you need to call during these lifecycle hooks.
To use them, add the following entries to the `scripts` property in the [.path]_package.json_ at the root of your project.

[,json]
----
"postpublish": "downdoc --postpublish",
"prepublishOnly": "downdoc --prepublish",
----

Let's have a look at where these entries go when we step back and look at a complete file:

[,json]
----
{
  "name": "my-package",
  "version": "1.0.0",
  "scripts": {
    "postpublish": "downdoc --postpublish",
    "prepublishOnly": "downdoc --prepublish",
    "test": "mocha"
  }
}
----

You can find an example of downdoc used for this purpose in the downdoc project itself.
endif::[]

== Copyright and License

Copyright (C) 2022-present Dan Allen (OpenDevise Inc.) and the individual contributors to this project.

Use of this software is granted under the terms of the MIT License.
